server:
  port: 8082

#resource: C:\\Users\\Administrator\\Desktop\\file
resource: C:\\Users\\12927\\Desktop\\file\\
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dzyh?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
  mapper-locations: classpath*:dao/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 逻辑未删除
      logic-not-delete-value: 0
      # 逻辑已删除
      logic-delete-value: 1
