server:
  port: 8089


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dzyh?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

dbNames: db_dzyh
dbFilePath: C:\\Users\\Administrator\\Desktop\\file\\db\\
hostIp: 127.0.0.1